### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Matheus7OP**
- Automatized setup and running for test 'warmup0';
- Updated README.md for 'warmup0'.

### CODE REVIEW

**Review by anayaml — APPROVED** [review]

**Review by thiagoyeds — APPROVED** [review]

**Comment by thiagomanel** [comment]
@Matheus7OP it'd be good to rebase you code before merging (since master was updated). If you do not know how to rebase, tell me.

**Comment by thiagomanel** [comment]
Also, it is not ok to commit suge huge file. Note that, as the input is random data, you can call the script to generate the data in the setup.sh

**Review by thiagomanel — CHANGES_REQUESTED** [review]
what is this execute directory? Also, check my general comments

**Review by thiagomanel — CHANGES_REQUESTED** [review]
read the master code. Verify that we read URLs from the conf files, instead of hardwiring the code in the scripts

**Pull request merged**
